spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      access-token-expiration: 86_400_000 # 24 hours
      refresh-token-expiration: 604_800_000 # 7 days