spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
jwt:
  secret: ${JWT_SECRET}
